### ISSUE TITLE
Pi 400 installation

### ISSUE THREAD

**Issue by blopblopblup** [arielnh56/shoptask1720#1]
Hi, I am currently setting up a PI 400 with a 7i96 but linuxcnc is giving me a lot of trouble. 
Would you mind sharing what you went through to get it working ?
Thank you in advance :)

**Comment by arielnh56** [comment]
I set it up witn the Noobs dual boot, and for linuxcnc image I started with the minimal 32bit raspbian and added the x-windows gui then followed the linuxcnc install wiki. The only tweak to config is to limit memory to 3GB - there was a problem with usb otherwise. Internal wifi and power switch don't work, I'm using external parts for that.
